### ISSUE TITLE
JCF Dropdown crashing after options have been changed with angular

### ISSUE THREAD

**Issue by GBora** [w3co/jcf#9] opened 2015-09-01 06:11 UTC
Initially the dropdown works as intended but after I change the list of options for the dropdown (the user changes languages and I load a list of options in the appropriate language) the plugin fails to redraw and the options are rendered as small gray divs with no text in them.

**Comment by inferpse** [comment] 2015-09-01 08:57
Hi, @GBora !
What version do you use? How to reproduce the issue?
I've created [plnkr](http://plnkr.co/edit/KiYhtpsD3hJwKYgbDc8s?p=preview) to test the issue with the most recent version of JCF module - it seems to work properly.

Please check that your `<li>` inside the custom dropdown has minimal height set in CSS.

**Comment by GBora** [comment] 2015-09-01 13:42
Hi @inferpse 

I'm using version 1.2.0 installed via bower.

Your plunkr is quite different from my sittuation in that I change the options via angular, so we're talking a controller and a service making the http call in the mix.

I'll check my styles and see if a minimal height helps.

**Comment by inferpse** [comment] 2015-09-01 14:15
Ok, I'll be waiting for your feedback. It would be great if you could provide some piece of code/data you use to populate select options.

**Comment by GBora** [comment] 2015-09-02 07:46
@inferpse I've checked and when I change the options with angular, there are no '<li>' elements at all they're not being generated even though I'm using `jcf.refreshAll()`.

http://codepen.io/anon/pen/ZbEVqO

This is how I'm updating the options the angular part, I started doing it on codepen but then I noticed I can't add jcf there to complete, but the ideea is after I get the new data I refreshAll and not new options are generated.

**Comment by inferpse** [comment] 2015-09-02 19:52
@GBora I've forked your pen and added JCF module to test the issue - http://codepen.io/anon/pen/VvYwYw
According to the angular docs it's better to use `ng-options` directive instead of `<option ng-repeat="...">` for performance reasons, so I've changed that in the pen.

I can't reproduce your issue with blank dropdown. Could you modify the pen, so we can see it?

**Comment by GBora** [comment] 2015-09-02 20:53
@inferpse Thanks for forking the pen.

Unfortunately the real behaviour of the app is more complex, in that I'm making a lot of calls and manny dropdowns are getting new options, might that have something to do with it ?

Also I noticed you're not calling refreshAll to redraw the dropdown is that a mistake on my part ? As I'm bring in new data I have to refresh a lot of jcf components so that's why I'm using the method.

I'll close the issue as it's obviously something wrong with the structure of my app and not with the library but I'd like to hear your thoughts.

**Comment by inferpse** [comment] 2015-09-03 09:36
@GBora Do you use `jcf.angular.js` file in your Angular project? This is simple directive which is designed to initialize, refresh and destroy custom form elements **automatically**, so you don't need to use JCF API at all (check out the source code of that directive). If you're not using it - try to remove all `jcf.replaceAll()` and `jcf.refreshAll()` methods and simply add `jcf` attribute to the form element.

You can help me to understand why the dropdown is broken if you'll inspect the styles and structure of the dropdown.

**Comment by inferpse** [comment] 2015-09-28 09:05
I've closed this issue. Feel free to comment it, so we could reproduce and fix the problem.

**Closed by inferpse** 2015-09-28 09:05 UTC
